name: Deploy to VPS

on:
  push:
    branches:
      - main
      - 3-fix-ci-cd
      
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
#      - name: Debug SSH connection
 #       run: ssh -vvv -o StrictHostKeyChecking=no -i "${{ secrets.VPS_PRIVATE_KEY }}" debian@${{ secrets.VPS_HOST }}

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: "debian"
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            eval "$(ssh-agent -s)"
            ssh-add ~/.ssh/github_deployment_key
            cd /home/debian/FlagQuest/
            git pull
            cd backend
            npm install
            npm run build
            cd dist
            pm2 restart main
