name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Debug SSH connection
        run: ssh -vvv -i ${{ secrets.VPS_PRIVATE_KEY }} ${{ secrets.VPS_USER_NAME }}@${{ secrets.VPS_HOST }}

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER_NAME }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          script: |
            cd /home/debian/FlagQuest/
            git pull origin main
            cd backend
            npm install
            npm run build
            cd dist
            pm2 restart main
